package com.epam.preprod.sirenko.strategy.impl;

import com.epam.preprod.sirenko.entity.Food;
import com.epam.preprod.sirenko.strategy.Strategy;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;

import static org.mockito.Mockito.mock;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;

class FoodFactoryImplTest {
	
	@Test
	void createProductShouldCreateNewProduct() {
		Strategy strategy = mock(AutoGeneratedProductCreationStrategy.class);
		when(strategy.getBigDecimal()).thenReturn(BigDecimal.ONE);
		when(strategy.getStringName()).thenReturn("Name");
		when(strategy.getInt()).thenReturn(10);
		FoodFactoryImpl foodFactory = new FoodFactoryImpl(strategy);
		
		Food product = (Food) foodFactory.createProduct();
		
		assertNotNull(product);
		assertEquals(BigDecimal.valueOf(1), product.getPrice());
		assertEquals("Name", product.getName());
		assertEquals(10, product.getWeight());
	}
}