package com.epam.preprod.sirenko.strategy.impl;

import com.epam.preprod.sirenko.enums.PetGroup;
import com.epam.preprod.sirenko.enums.Season;
import com.epam.preprod.sirenko.enums.Size;
import com.epam.preprod.sirenko.strategy.Strategy;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Random;

public class AutoGeneratedProductCreationStrategy implements Strategy {
	private static final Random RANDOM = new Random();
	private static final char[] ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".toCharArray();
	
	@Override
	public PetGroup getPetGroup() {
		return PetGroup.values()[RANDOM.nextInt(PetGroup.values().length)];
	}
	
	@Override
	public Season getSeason() {
		return Season.values()[RANDOM.nextInt(Season.values().length)];
	}
	
	@Override
	public Size getSize() {
		return Size.values()[RANDOM.nextInt(Size.values().length)];
	}
	
	@Override
	public String getStringName() {
		StringBuilder stringBuilder = new StringBuilder();
		for (int i = 0; i < 10; i++) {
			char letter = ALPHABET[RANDOM.nextInt(ALPHABET.length)];
			stringBuilder.append(letter);
		}
		return stringBuilder.toString();
	}
	
	@Override
	public String getStringBrandName() {
		return getStringName();
	}
	
	@Override
	public int getInt() {
		return RANDOM.nextInt(1000);
	}
	
	@Override
	public BigDecimal getBigDecimal() {
		return new BigDecimal(BigInteger.valueOf(RANDOM.nextInt(100001)), 2);
	}
}