package com.epam.preprod.sirenko.strategy;

import com.epam.preprod.sirenko.enums.PetGroup;
import com.epam.preprod.sirenko.enums.Season;
import com.epam.preprod.sirenko.enums.Size;
import com.epam.preprod.sirenko.strategy.impl.AutoGeneratedProductCreationStrategy;
import com.epam.preprod.sirenko.strategy.impl.ManualProductCreationStrategy;

import java.math.BigDecimal;

public interface ProductCreationNoReflectionStrategy {
	ManualProductCreationStrategy manualNoReflection();
	AutoGeneratedProductCreationStrategy autoNoReflection();
	
//	PetGroup getPetGroup();
//	Season getSeason();
//	Size getSize();
//	String getStringName();
//	String getStringBrandName();
//	int getInt();
//	BigDecimal getBigDecimal();
}
